### ISSUE TITLE
feat(crowdfund): allow crowdfund creators to set a min or max contribution size

### ISSUE THREAD

**Issue by 0xble** [PartyDAO/party-protocol#188]
### Describe the feature you would like

When initializing any crowdfund type, allow creators to set an optional minimum and/or maximum amount that can be contributed to the crowdfund by a contributor.

**Comment by RyanSea** [comment]
Hey, I'd like to take this on. Could you make a branch?

**Comment by 0xble** [comment]
> Hey, I'd like to take this on. Could you make a branch?

Absolutely, go ahead and make a PR when you're ready!
