### ISSUE TITLE
feat(crowdfund): allow contributing on another's behalf

### ISSUE THREAD

**Issue by 0xble** [PartyDAO/party-protocol#191]
### Describe the feature you would like

Add a `contributeFor()` function that allow the caller to contribute ETH to a crowdfund but have their contribution recorded under another address.

### Additional context

Requested feature by PleasrDAO

**Comment by RyanSea** [comment]
Is this closed?

**Comment by 0xble** [comment]
> Is this closed?

Not closed, but being worked on here: https://github.com/PartyDAO/party-protocol/pull/192

Welcome to any suggestions or contributions on this PR though!
