### ISSUE TITLE
feat(crowdfund): add ability to rage quit

### ISSUE THREAD

**Issue by 0xble** [PartyDAO/party-protocol#193]
### Describe the feature you would like

Inspired by the rage quit feature from MolochDAO, allow crowdfund contributors to "rage quit" by exiting from crowdfunds they've contributed to and receiving back their original contribution amount before the crowdfund has been finalized.

**Comment by addyxvii** [comment]
I started working on this, and was wondering the preferred way of making a pr since I don't believe I permissions to push a new branch in the repo.

Thanks!

**Comment by 0xble** [comment]
> I started working on this, and was wondering the preferred way of making a pr since I don't believe I permissions to push a new branch in the repo.
> 
> Thanks!

Hey, thanks for the interest!

To push a PR you'll have to fork this repo and create a PR from your fork, but just want to give a heads up that keeping the `previousTotalContributions` field stored for every contribution up-to-date when contributors can withdraw their contributions does seem to make implementing this tricky.

**Comment by addyxvii** [comment]
What's the reason `previousTotalContributions` need to be up to date, and not just removed when a user withdraws? For preserving metrics on a crowdfund? My first pass I had just removed that contributors mapping

**Comment by 0xble** [comment]
> What's the reason `previousTotalContributions` needs to be up to date, and not just removed when a user withdraws? For preserving metrics on a crowdfund? My first pass I had just removed that contributors mapping

It's used to determine whether a contributors contribution was used or not

**Comment by addyxvii** [comment]
For clarification, is there a case where a contributors contribution would be used before the crowdfund is finalized?, and second question, once a user rage quits should they be allowed to come back and contribute again? or does rage quitting disqualify them from future contributions?

**Comment by 0xble** [comment]
> I was being thick but get it now, currently there is the `_contributionsByContributor` mapping, but no array of contributors, and that would be needed to update every contributors `previousTotalContributions` without that being updated the amount of contributions, used and/or owed to a contributor would be incorrect as soon as someone withdrew their contribution.

Yes, but storing an array of every contributors would be impractical. Perhaps you could store a new variable like `totalContributionsWithdrawn` and factor it into all the places where contribution accounting occurs?

**Comment by addyxvii** [comment]
I opened a PR [here](https://github.com/PartyDAO/party-protocol/pull/219) I tried to add labels, but don't think I have permission
