### ISSUE TITLE
feat(crowdfund): support crowdfunds for ERC1155s

### ISSUE THREAD

**Issue by 0xble** [PartyDAO/party-protocol#201]
### Describe the feature you would like

Party Protocol currently only supports ERC721 crowdfunds, but there has been demand for ERC1155s too.

Things to explore:
- How hard would that be?
- Can we upgrade existing crowdfunds or do we need new ones?
- Any other important details to consider?

**Comment by RyanSea** [comment]
For crowdfunds, it seems like you can change LibSafeERC721 into a 'LibSafeNFT', where safeOwnerOf checks interface, and / or try..catches, to return either ownerOf (if 721) or balanceOf (if 1155). Might be more to do for parties

**Comment by 0xble** [comment]
> For crowdfunds, it seems like you can change LibSafeERC721 into a 'LibSafeNFT', where safeOwnerOf checks interface, and / or try..catches, to return either ownerOf (if 721) or balanceOf (if 1155). Might be more to do for parties

Yeah that would be a change we'd need to do
