### ISSUE TITLE
feat: update to latest Solidity version

### ISSUE THREAD

**Issue by 0xble** [PartyDAO/party-protocol#227]
### Describe the feature you would like

All contracts are from an older version of Solidity (0.8.17). These should be updated to the latest version.

**Comment by daredevil3435** [comment]
can you explain more in details. I would like to contribute.

**Comment by 0xble** [comment]
> can you explain more in details. I would like to contribute.

Yeah definitely! It's pretty simple, it'd just involve updating the contracts and test to Solidity version 0.8.19. If any issues come up with this (which I don't think they will, but could be wrong) let us know.

Part of this would should also involve taking advantage of the new named parameters in mapping types introduced in 0.8.18 and updating the mappings used in contracts.

**Comment by AnmolSirola** [comment]
@0xble Is anyone still working on this issue ?

**Comment by 0xble** [comment]
> @0xble Is anyone still working on this issue ?

This one has been covered, thanks for checking!
