### ISSUE TITLE
Add new market for Nouns Builder DAOs

### ISSUE THREAD

**Issue by Yiwen-Gao** [PartyDAO/party-protocol#231]
### Describe the feature you would like

[Nouns Builder](https://nouns.build/) is a project by Zora, and it makes it easy for anyone to create a DAO in the style of NounsDAO (e.g. some of the key features include recurring auctions for governance tokens and upgradable contract design). However, even though Nouns Builder DAOs were started by Zora and are similar in functionality to NounsDAO, they don't conform to PartyBid's auction houses for either Zora or Nouns. We discovered this issue when attempting to start a group bid for a [PurpleDAO](https://nouns.build/dao/0xa45662638e9f3bbb7a6fecb4b17853b7ba0f3a60/213) auction, with PurpleDAO being one of the most popular Nouns Builder DAOs.

**Comment by 0xble** [comment]
Closing because it has been implemented, thanks @Yiwen-Gao!
